name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q tests/test_create_site.py

  accept-pull-request:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Auto-merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Usa a ferramenta CLI nativa do GitHub para mesclar o PR atual via Squash
          gh pr review ${{ github.event.pull_request.number }} --approve --body
